/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 14 14:43:30 GMT 2016
 */

package capstone.mobile.dataHandlers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import capstone.mobile.dataHandlers.RetrieveData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RetrieveData_ESTest extends RetrieveData_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 13 covered goals:
   * Goal 1. fetchTrapsList(I)Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 74
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 75
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 76
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 98
   * Goal 6. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 99
   * Goal 7. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;
   * Goal 8. Weak Mutation 17: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/trap?line_id= -> 
   * Goal 9. Weak Mutation 18: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp Negation of lineId
   * Goal 10. Weak Mutation 19: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp IINC 1 lineId
   * Goal 11. Weak Mutation 20: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp IINC -1 lineId
   * Goal 12. Weak Mutation 21: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - ReplaceComparisonOperator == -> !=
   * Goal 13. Weak Mutation 22: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:75 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      try { 
        RetrieveData.fetchTrapsList(0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 1
  /*
   * 12 covered goals:
   * Goal 1. fetchTrapsList(I)Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 74
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 75
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 76
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;: Line 78
   * Goal 6. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;
   * Goal 7. Weak Mutation 17: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/trap?line_id= -> 
   * Goal 8. Weak Mutation 18: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp Negation of lineId
   * Goal 9. Weak Mutation 19: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp IINC 1 lineId
   * Goal 10. Weak Mutation 20: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - InsertUnaryOp IINC -1 lineId
   * Goal 11. Weak Mutation 21: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:74 - ReplaceComparisonOperator == -> !=
   * Goal 12. Weak Mutation 22: capstone.mobile.dataHandlers.RetrieveData.fetchTrapsList(I)Ljava/util/List;:75 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/trap?line_id=1");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      // Undeclared exception!
      try { 
        RetrieveData.fetchTrapsList(1);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. fetchLinesList()Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 33
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 34
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 35
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 60
   * Goal 6. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 61
   * Goal 7. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;
   * Goal 8. Weak Mutation 0: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:33 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/line -> 
   * Goal 9. Weak Mutation 1: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:33 - ReplaceComparisonOperator == -> !=
   * Goal 10. Weak Mutation 2: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:34 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      try { 
        RetrieveData.fetchLinesList();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 3
  /*
   * 9 covered goals:
   * Goal 1. fetchLinesList()Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 33
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 34
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 35
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;: Line 37
   * Goal 6. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;
   * Goal 7. Weak Mutation 0: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:33 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/line -> 
   * Goal 8. Weak Mutation 1: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:33 - ReplaceComparisonOperator == -> !=
   * Goal 9. Weak Mutation 2: capstone.mobile.dataHandlers.RetrieveData.fetchLinesList()Ljava/util/List;:34 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/line");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "capstone.mobile.dataHandlers.DataUnavailableException");
      // Undeclared exception!
      try { 
        RetrieveData.fetchLinesList();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 4
  /*
   * 10 covered goals:
   * Goal 1. fetchAnimalList()Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 110
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 111
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 112
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 137
   * Goal 6. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 138
   * Goal 7. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;
   * Goal 8. Weak Mutation 39: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:110 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/animal -> 
   * Goal 9. Weak Mutation 40: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:110 - ReplaceComparisonOperator == -> !=
   * Goal 10. Weak Mutation 41: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:111 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      try { 
        RetrieveData.fetchAnimalList();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * Goal 1. fetchAnimalList()Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 110
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 111
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 112
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;: Line 114
   * Goal 6. [METHOD] capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;
   * Goal 7. Weak Mutation 39: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:110 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/animal -> 
   * Goal 8. Weak Mutation 40: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:110 - ReplaceComparisonOperator == -> !=
   * Goal 9. Weak Mutation 41: capstone.mobile.dataHandlers.RetrieveData.fetchAnimalList()Ljava/util/List;:111 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/animal");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      // Undeclared exception!
      try { 
        RetrieveData.fetchAnimalList();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 6
  /*
   * 14 covered goals:
   * Goal 1. checkAuthorisation(ILjava/lang/String;)I_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 149
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 150
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 151
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 164
   * Goal 6. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 165
   * Goal 7. [METHOD] capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I
   * Goal 8. Weak Mutation 56: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/checkauth?line_id= -> 
   * Goal 9. Weak Mutation 57: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp Negation of lineId
   * Goal 10. Weak Mutation 58: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp IINC 1 lineId
   * Goal 11. Weak Mutation 59: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp IINC -1 lineId
   * Goal 12. Weak Mutation 60: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceConstant - &password= -> 
   * Goal 13. Weak Mutation 61: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceComparisonOperator == -> !=
   * Goal 14. Weak Mutation 62: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:150 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      try { 
        RetrieveData.checkAuthorisation(3161, "j%Q-%");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 7
  /*
   * 4 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.RetrieveData.<init>()V: root-Branch
   * Goal 2. Branch capstone.mobile.dataHandlers.RetrieveData.<init>()V: root-Branch in context: capstone.mobile.dataHandlers.RetrieveData:<init>()V
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.RetrieveData.<init>()V
   * Goal 4. [METHODNOEX] capstone.mobile.dataHandlers.RetrieveData.<init>()V
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RetrieveData retrieveData0 = new RetrieveData();
  }
}
