/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 14 14:43:30 GMT 2016
 */

package evosuite.dataHandlers;

import capstone.mobile.dataHandlers.RetrieveData;
import org.junit.Test;

import static org.junit.Assert.fail;

public class RetrieveData_ESTest {

    //Test case number: 6
  /*
   * 14 covered goals:
   * Goal 1. checkAuthorisation(ILjava/lang/String;)I_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 149
   * Goal 3. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 150
   * Goal 4. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 151
   * Goal 5. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 164
   * Goal 6. capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I: Line 165
   * Goal 7. [METHOD] capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I
   * Goal 8. Weak Mutation 56: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceConstant - https://traptracker.pythonanywhere.com/api/checkauth?line_id= -> 
   * Goal 9. Weak Mutation 57: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp Negation of lineId
   * Goal 10. Weak Mutation 58: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp IINC 1 lineId
   * Goal 11. Weak Mutation 59: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - InsertUnaryOp IINC -1 lineId
   * Goal 12. Weak Mutation 60: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceConstant - &password= -> 
   * Goal 13. Weak Mutation 61: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:149 - ReplaceComparisonOperator == -> !=
   * Goal 14. Weak Mutation 62: capstone.mobile.dataHandlers.RetrieveData.checkAuthorisation(ILjava/lang/String;)I:150 - ReplaceComparisonOperator == -> !=
   */

    @Test(expected = Exception.class)
    public void test6() throws Throwable {
        RetrieveData.checkAuthorisation(3161, "j%Q-%");
        fail("Expecting exception: Exception");
    }

    //Test case number: 7
  /*
   * 4 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.RetrieveData.<init>()V: root-Branch
   * Goal 2. Branch capstone.mobile.dataHandlers.RetrieveData.<init>()V: root-Branch in context: capstone.mobile.dataHandlers.RetrieveData:<init>()V
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.RetrieveData.<init>()V
   * Goal 4. [METHODNOEX] capstone.mobile.dataHandlers.RetrieveData.<init>()V
   */

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        RetrieveData retrieveData0 = new RetrieveData();
    }
}
