/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 14 14:47:41 GMT 2016
 */

package capstone.mobile.dataHandlers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import capstone.mobile.dataHandlers.LocalDatabase;
import capstone.mobile.models.Capture;
import capstone.mobile.models.Line;
import capstone.mobile.models.Trap;
import capstone.mobile.models.Walk;
import java.sql.SQLException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LocalDatabase_ESTest extends LocalDatabase_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V: Line 243
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V: Line 246
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V: Line 247
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V: Line 249
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.setCurrentLine(Lcapstone/mobile/models/Line;)V
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Line line0 = new Line();
      LocalDatabase.setCurrentLine(line0);
      assertEquals(0, line0.getId());
  }

  //Test case number: 1
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V: Line 90
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V: Line 132
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V: Line 133
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V: Line 135
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.loadDatafromLocalDatabase(Lcapstone/mobile/models/Walk;)V
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Walk walk0 = new Walk();
      LocalDatabase.loadDatafromLocalDatabase(walk0);
      assertFalse(walk0.isDirection());
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.endWalk()V: Line 224
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.endWalk()V: Line 232
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.endWalk()V: Line 233
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.endWalk()V: Line 235
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.endWalk()V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.endWalk()V
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDatabase.endWalk();
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V: Line 158
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V: Line 164
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V: Line 165
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V: Line 167
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.changeTrap(Lcapstone/mobile/models/Trap;)V
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDatabase.changeTrap((Trap) null);
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V: Line 175
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V: Line 179
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V: Line 180
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V: Line 182
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.addNewTrap(Lcapstone/mobile/models/Trap;)V
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalDatabase.addNewTrap((Trap) null);
  }

  //Test case number: 5
  /*
   * 6 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V: Line 143
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V: Line 147
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V: Line 148
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V: Line 150
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V
   * Goal 6. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.addCapture(Lcapstone/mobile/models/Capture;)V
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDatabase.addCapture((Capture) null);
  }

  //Test case number: 6
  /*
   * 6 covered goals:
   * Goal 1. updateTraps(I)Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;: Line 192
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;
   * Goal 4. Weak Mutation 85: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp Negation of lineId
   * Goal 5. Weak Mutation 86: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp IINC 1 lineId
   * Goal 6. Weak Mutation 87: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp IINC -1 lineId
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      try { 
        LocalDatabase.updateTraps((-19));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 7
  /*
   * 6 covered goals:
   * Goal 1. updateTraps(I)Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;: Line 192
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;
   * Goal 4. Weak Mutation 85: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp Negation of lineId
   * Goal 5. Weak Mutation 86: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp IINC 1 lineId
   * Goal 6. Weak Mutation 87: capstone.mobile.dataHandlers.LocalDatabase.updateTraps(I)Ljava/util/List;:192 - InsertUnaryOp IINC -1 lineId
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/trap?line_id=1220");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      // Undeclared exception!
      try { 
        LocalDatabase.updateTraps(1220);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 8
  /*
   * 3 covered goals:
   * Goal 1. updateLines()Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateLines()Ljava/util/List;: Line 259
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateLines()Ljava/util/List;
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      try { 
        LocalDatabase.updateLines();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 9
  /*
   * 3 covered goals:
   * Goal 1. updateLines()Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateLines()Ljava/util/List;: Line 259
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateLines()Ljava/util/List;
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/line");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "3%wUh-7l");
      // Undeclared exception!
      try { 
        LocalDatabase.updateLines();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 10
  /*
   * 3 covered goals:
   * Goal 1. updateAnimals()Ljava/util/List;_org.evosuite.runtime.mock.java.lang.MockException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateAnimals()Ljava/util/List;: Line 289
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateAnimals()Ljava/util/List;
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      try { 
        LocalDatabase.updateAnimals();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Could not find: traptracker.pythonanywhere.com
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * Goal 1. updateAnimals()Ljava/util/List;_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.updateAnimals()Ljava/util/List;: Line 289
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.updateAnimals()Ljava/util/List;
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("https://traptracker.pythonanywhere.com/api/animal");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "YtVNGY}.tw");
      // Undeclared exception!
      try { 
        LocalDatabase.updateAnimals();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/json/Json
         //
         assertThrownBy("capstone.mobile.dataHandlers.RetrieveData", e);
      }
  }

  //Test case number: 12
  /*
   * 3 covered goals:
   * Goal 1. setUpLocalDatabase()V_java.lang.NoClassDefFoundError_IMPLICIT
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.setUpLocalDatabase()V: Line 26
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.setUpLocalDatabase()V
   */

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        LocalDatabase.setUpLocalDatabase();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/gluonhq/charm/down/common/PlatformFactory
         //
         assertThrownBy("capstone.mobile.dataHandlers.LocalDatabase", e);
      }
  }

  //Test case number: 13
  /*
   * 5 covered goals:
   * Goal 1. fetchLines()Ljava/util/List;_java.sql.SQLException_DECLARED
   * Goal 2. capstone.mobile.dataHandlers.LocalDatabase.fetchLines()Ljava/util/List;: Line 318
   * Goal 3. capstone.mobile.dataHandlers.LocalDatabase.fetchLines()Ljava/util/List;: Line 319
   * Goal 4. capstone.mobile.dataHandlers.LocalDatabase.fetchLines()Ljava/util/List;: Line 331
   * Goal 5. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.fetchLines()Ljava/util/List;
   */

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      try { 
        LocalDatabase.fetchLines();
        fail("Expecting exception: SQLException");
      
      } catch(SQLException e) {
         //
         // The url cannot be null
         //
         assertThrownBy("java.sql.DriverManager", e);
      }
  }

  //Test case number: 14
  /*
   * 4 covered goals:
   * Goal 1. capstone.mobile.dataHandlers.LocalDatabase.<init>()V: root-Branch
   * Goal 2. Branch capstone.mobile.dataHandlers.LocalDatabase.<init>()V: root-Branch in context: capstone.mobile.dataHandlers.LocalDatabase:<init>()V
   * Goal 3. [METHOD] capstone.mobile.dataHandlers.LocalDatabase.<init>()V
   * Goal 4. [METHODNOEX] capstone.mobile.dataHandlers.LocalDatabase.<init>()V
   */

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDatabase localDatabase0 = new LocalDatabase();
  }
}
